name: mypersonalapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  intl: ^0.19.0
  provider: ^6.1.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.4
  cloud_functions: ^4.6.5
  change_app_package_name: ^1.4.0
  percent_indicator: ^4.2.4
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    # - assets/google_logo.png
    # - assets/task_list.png
    # - assets/no_task.jpeg
    # - assets/avatar.png